# Translating lessons from response to applied routine epidemic intelligence

This document sets out the simple strategy for what I would like to do and how I would like to develop my career with support from an NIHR fellowship.

--------------------------------------------------------------------------------

## Review questions

1. Internal coherence

- Do the 3 research aims and work packages make sense individually and as a coherent whole?
- What is a succinct single-sentence aim for each of the 3 work packages word the 3 headline aims to match the intent/scope of the proposed work?

2. Consistency with my interests and values

- Do the 3 work packages appropriately reflect my research interests and current plans, documented elsewhere (applications, kath-a-log)?
- As an overall career interest, I would ideally like to make an explicit link to risk in my work (considering risk = hazard x exposure x vulnerability); is there a coherent, consistent way to approach this in part or all of the suggested work, or would it be forcing an unnecessary structure?

3. Feasibility and evaluation of proposed work:

- This proposal moves between three different epidemiological quantities: R/growth rate (aim 1), excess deaths (aim 2), case/hospitalisation forecasting (aim 3); is this sensible, and what are the key challenges and opportunities from this?
- Aim 2 is the newest in my thinking: does it make sense as a whole; does the demand/supply regime comparison hold up; what can be improved?
- Aim 3 is the broadest; what is the simplest and most consistent way to tighten this up using my existing notes and thinking on UK modelling and local forecasting dynamics?
- Do the 3 career development aims seem sensible and consistent with the research aims?

--------------------------------------------------------------------------------

## Overall strategy

Novel research:

1. Evaluate the consensus model of SPI-M for producing epidemic intelligence in crisis
2. Compare to the evolution and production of ONS excess death statistics
3. Improve forecasting in coupled supply-demand systems on response to seasonal winter pressures

Career development:

1. Establish myself as a trusted and respected researcher in real-time crisis epidemiology
2. Understand the development and tensions of excess mortality statistics, equipped to apply to international and conflict settings
3. Create tangible improvements in the quality, value, and trust in local authority or NHS trust level use of statistical and modelling tools for decision support

--------------------------------------------------------------------------------

## Research

1. 

I want to evaluate the SPI-M consensus model for producing estimates of the reproduction number (R) and growth rate (r; combined referred to as R/r) during COVID-19.

Model evaluation includes:

- Qualification: Infrastructure and assumptions (SPI-M history, recruitment, assumptions)
- Verification: Process of expert elicitation, and use of language of uncertainty
- Validation: Calibration and combination of individual model estimates against best estimates

2. 

I then want to use the ONS estimation of excess deaths as a comparator to production of SPI-M consensus statements.

- These numbers share similar challenges in estimation.
  They are are both unobservable, time-lagged, censored, and an often biased summary of heterogeneous epidemiological patterns.
  This creates parametric uncertainty (any method produces an uncertain estimate), structural uncertainty (there is no single best method for estimation), and unclear responsibility (?).
- During COVID-19, both estimands were highly policy salient and the subject of constant public scrutiny.
- The central difference is the mode of production.
  SPI-MO is an ad hoc, voluntary, responsive group of experts responding to a specific policy situation: it is demand-driven.
  SPI-MO consensus statements had no clear criteria for their content, but R/growth rate emerged as the consistent product.
  ONS is an formal, funded, routine producer of all official statistics: it is supply-driven.
  Excess death statistics are a single well-defined product.

Comparison of these two modes of production to focus on:

- Quality: real-time evaluation (peer review)
- Value: language of uncertainty in consensus statements and published ONS outputs
- Trust: allocation of responsibility

3. 

Lastly, I want to consider real-time forecasting of hospitalisations during seasonal winter pressures.
Forecasting seasonal demand lies between supply and demand regimes; neither demand nor supply are yet settled.
Demand is cyclical (informed by annual JCVI vaccine strategy, seasonal capacity/budget planning).
There is increasing interest and capacity at UKHSA, and some evidence of ad hoc production within tightly coupled supply-demand settings (NHS, local authorities).
Quality assurance is likely highly variable.
Can we balance the lessons of both demand-driven and supply-driven modelling regimes to implement high-quality forecasting and directly improve the use of modelling for real-time decision support?

Work to include:

- Supply: mapping UK modelling expertise
- Demand: mapping UK decision-making under seasonal pressures
- Production: considering alternative ways to match supply with demand (forecast challenges; academic working group consensus; academic public health placements; improving within the demand setting e.g. UKHSA estimates).
  Potentially start with evaluation in UKHSA; real interest in tightly-coupled supply-demand systems (NHS trusts, local authorities)

--------------------------------------------------------------------------------

CONTEXT

Some previous text is below.
See also: all materials in nihr/ and wellcome/ directories, and kath-a-log/greenhouse, for more fleshed out ideas.

--------------------------------------------------------------------------------

## Quality

1. The reproduction number & growth rate Rationale:
   - Epidemiological quality: representation of underlying transmission
   - Policy value: Use in prospectively driving policy
   - Public trust: Representation, process of production

2. Short & medium term forecasts Rationale:
   - Quality: accuracy against observed data (relevance: fastest area of improved methodology i.e. nowcasting)
   - Value: informs operational response e.g. capacity ovewhelm
   - Trust:

2. Excess/Avoidable deaths Rationale:
   - Quality: captures sequelae & Long Covid
   - Value: Use for assessing effect of better interventions
   - Trust: best retrospective indicator of overall societal impact

## Value

- History of spi-m i.e. political rationale
- Handling of uncertainty vs risk
  - Language of consensus statements: where/when is language of uncertainty used?
    - statements are full of phrases around estimates: "best estimate", "there is evidence that", "there is uncertainty in X region"
    - how often are statements about uncertain quantities framed using language of uncertainty?
- user value, spi-m secretariat

## Trust

- Consensus process, biases, psychological safety, quality assurance
- Responsibility: 3 lines model; role in emergencies v routine analysis
- Learning & source network of expertise

#### Role of SPI-M vs. UKHSA

*Background*.
In COVID-19, SPI-M provided an "equal consensus" approach to comparing and combining evidence from multiple models.
Thanks to a (good) expansion of capacity and skill within UKHSA, during Pegasus we saw a clearer steer towards a "champion/challenge" model.
In this format, the UKHSA produces estimates for relevant policy questions, and SPI-M's role is to challenge based on expertise.
Rather than comparing among modelling work equally, we have a kind of strong prior to be confronted and updated with other models/expertise.

*Challenge.* This led to substantial confusion during Pegasus: it was unclear whether the function of SPI-M was to produce meaningful analysis, to describe their intended analysis, or to provide peer review/critique of UKHSA analysis.
Without clarity on what UKHSA was planning to or capable of producing, it was difficult to avoid duplicated effort; and unclear when duplicated effort was the intention, i.e. scientific replication, vs redundant.
By contrast, we could have spent this time supporting UKHSA in their internal process, e.g. reviewing code or supporting tool adoption.

*Implications.*

- Operational.
  We need to clarify UKHSA capacity both in advance (ideally working with them on whatever their internal protocol is for outbreak response), and in real-time (e.g. code sharing).\
- Epistemic*.* The champion/challenge format changes how we produce and evaluate evidence.\
  - *Function.* When might we actually need multiple independent models (to complement UKHSA), rather than critique?
    Are there some policy questions we should prioritise for challenge?\
  - *Process*.
    We could consider UKHSA estimates as an "informative prior".
    How could/should UKHSA estimates be adjusted based on other work (e.g. weighted)?\
  - *Outputs*.
    How do we write a representative consensus statement in this format?
    How is the language of consistency/conflict expressed, and interpreted (e.g. "Other models were broadly consistent with"), relative to known uncertainty?

#### SPI-M-O, expert elicitation, and group dynamics

*Background*.
Modelling work is particularly useful as a system for integrating across a patchwork of highly uncertain sources.
This uncertainty also means that modelling work is highly flexible to individual analytical choices, and open to interpretation.
As a result, there is no single "best" source of modelling evidence from which to draw policy advice.
The SPI-M-O group is specifically convened to provide this diversity, from which to create a consensus of evidence for policy decisions.
In addition, there is strong evidence that experts working in small groups can enable better (more accurate, creative) outcomes.

*Challenge*.
However, this can also be compromised by (1) recruitment, needing to balance both relevance and diversity of expertise; and (2) group facilitation, to avoid biases in group decision-making (which could be individual, e.g. anchoring, ease of recall; or social, e.g. groupthink, "halo" effects).
The real-time pressure of emergencies may add to these effects in either direction, while also making it very difficult to capture, report, and consider the impact of such dynamics.
Nonetheless, addressing groupthink in advisory processes was a specific recommendation of the UK COVID-19 Inquiry.
As far as I'm aware, there has been little work addressing this within scientific advisory groups in outbreak modelling (if not in other fields).

*Implications.* In the context of SPI-M: it's not always clear how/when quantitative work informs qualitative discussion; or the influence of the qualitative discussion on a resulting consensus statement.
I can imagine several ways to look at this:

- Clarifying and comparing the role of SPI-M-O in convening discussions, versus asking for and providing quantitative estimates alone\
- Reviewing concepts from judgement and decision-making literature, where these could be applied to SPI-M processes\
- Trialling validated tools for expert elicitation (for example, DELPHI or SHELF methods)\
- Reviewing and considering (existing) civil service standards for both (1) group facilitation for policy decision-making and (2) quality control of "business-critical" modelling work in the civil service\
- Guidance for communicating the extent of uncertainty, consensus, and conflict around decision making thresholds

## Evaluating the calibration of SPI-M consensus statements

Background:\
During COVID-19, the UK's Scientific Advisory Group for Emergencies relied on "consensus statements" produced by the epidemiological modelling sub-group, SPI-M.
It is useful to evaluate the accuracy of these statements.

Methods:

- Mine text of all consensus statements for probabilistic language\
- Metadata: date, contributors, topics covered, policy context\
- Take individual statements and match to framework of uncertainty language\
- Match consistency in statements about specific quantities over time: e.g. changes in direction\
- Where quantities can be measured, assess against observed data\
- Note language of disagreement, caveats\
- Note references to quantity and clarity of supporting evidence

Example results:

- Among all evaluable probabilistic statements calibration was X\
- Bias in the direction of Y\
- Stratified by\
  - Variant phase\
  - Variant competition (introduction vs dominance)\
  - Type of evidence supporting\
  - Number of contributors\
- Statements about A were X internally consistent\
- Caveats were present in X% statements\
- X statements were presented with directly supporting evidence

Interpretation:

- Potentially: compare to frameworks for writing consensus statements
- Potentially: compare to frameworks for writing consensus statements
